version: '3.8'
services:
  db:
    image: mysql:5.7.32
    restart: always
    environment:
      - MYSQL_DATABASE=nestjs-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=asdf1234
      - MYSQL_ROOT_PASSWORD=asdf1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: nest-api
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: nest-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: root
      DB_PW: asdf1234   
    links:
      - db
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/main.js"]
    env_file:
      - .env

volumes:
  db:
    driver: local